CREATE TABLE TBL_PLATFORM_PERMISSION (
    REQUESTER_CD        VARCHAR2(100) NOT NULL, 
	IP                  VARCHAR2(100) NOT NULL, 
	SERVICE_CD          VARCHAR2(100) NOT NULL, 
	SECRET_KEY          VARCHAR2(100), 
	REMARK_STR          VARCHAR2(1000), 
	REG_DATE            DATE, 
	CONSTRAINT TBL_PLATFORM_PERMISSION_PK PRIMARY KEY (REQUESTER_CD, IP, SERVICE_CD)
);

-- 코멘트 입력
COMMENT ON TABLE TBL_PLATFORM_PERMISSION  IS '권한관리';
COMMENT ON COLUMN TBL_PLATFORM_PERMISSION.REQUESTER_CD IS '요청자코드';
COMMENT ON COLUMN TBL_PLATFORM_PERMISSION.IP IS 'IP주소';
COMMENT ON COLUMN TBL_PLATFORM_PERMISSION.SERVICE_CD IS '서비스코드';
COMMENT ON COLUMN TBL_PLATFORM_PERMISSION.SECRET_KEY IS '비밀키';
COMMENT ON COLUMN TBL_PLATFORM_PERMISSION.REMARK_STR IS '설명';
COMMENT ON COLUMN TBL_PLATFORM_PERMISSION.REG_DATE IS '등록일자';


INSERT INTO TBL_PLATFORM_PERMISSION VALUES('TEST', '0.0.0.0', 'TEST', 'XPTMXM', '테스트', SYSDATE);

COMMIT;